DROP TABLE IF EXISTS Ward;
CREATE TABLE Ward(
    WardId SERIAL UNIQUE,
	HospitalId INT NOT NULL,
	ward_name VARCHAR(32) NOT NULL,
	ext_num VARCHAR(10),
	PRIMARY KEY (WardId),
	FOREIGN KEY (HospitalId) REFERENCES Hospital(HospitalId) 
	ON DELETE CASCADE
);

SELECT * FROM Ward;